version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  app_hot_reload:
    build:
      context: .
      args:
        env: dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env