#!/usr/bin/env bash

set -e

isort --recursive  --force-single-line-imports app
autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place app
black app
isort --recursive app
